// mp_vis_pack_compile_test — HLSL-compile smoke test for M3.1's shared
// pack/unpack helpers in shaders/micropoly/mp_vis_pack.hlsl.
//
// Purpose: validate that the include-only file PackMpVis64 + UnpackMpVis64
// are well-formed HLSL under the engine's exact DXC flag set (-Zpc -spirv
// -fspv-target-env=vulkan1.3 -HV 2021 -O3). The file itself is never
// referenced by any existing shader yet (callers land in M3.3/M3.4), so
// without this test a typo lands silently until those shaders ship.
//
// This test does NOT compare against a golden blob — mp_vis_pack.hlsl is
// deliberately excluded from the spirv_diff manifest (see banner in that
// HLSL file). We only check the SPIR-V blob is non-empty + the compile
// succeeds.
//
// Approach: synthesise a tiny wrapper compute shader string in-memory
// that #includes mp_vis_pack.hlsl, invokes both helpers, and writes the
// result into a buffer. Pipe that through the SpirvDiffHarness's DXC
// entry point via temp-file round-trip (compileOne takes a relativePath
// relative to shaderRoot — we put our wrapper in the same shaders/
// tree so the -I include path resolves mp_vis_pack.hlsl correctly).

#include "infra/spirv_diff/SpirvDiffHarness.h"

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>

#ifndef ENIGMA_SHADER_ROOT_DIR
#define ENIGMA_SHADER_ROOT_DIR ""
#endif

namespace {

namespace fs = std::filesystem;

// Minimal wrapper shader: includes mp_vis_pack, calls PackMpVis64 and
// UnpackMpVis64 so neither helper is DCE'd, and writes the round-trip
// result back out. Enough to prove the header parses and type-checks.
constexpr const char* kWrapperShader = R"HLSL(
// Generated by mp_vis_pack_compile_test — DO NOT EDIT
#include "mp_vis_pack.hlsl"

RWStructuredBuffer<uint64_t> g_out : register(u0);

[numthreads(1, 1, 1)]
void CSMain(uint3 dtid : SV_DispatchThreadID) {
    // M4.1 — vis-pack v2 signature: PackMpVis64(depth32, rasterClass,
    // clusterIdx, triangleIdx); UnpackMpVis64 emits all four fields.
    uint64_t packed = PackMpVis64(asuint(0.5f), kMpRasterClassHw, 123u, 7u);

    uint depth32     = 0u;
    uint rasterClass = 0u;
    uint cluster     = 0u;
    uint tri         = 0u;
    UnpackMpVis64(packed, depth32, rasterClass, cluster, tri);

    // Avoid dead-code elimination of both helpers.
    uint64_t sentinel = kMpVisEmpty;
    if (cluster == 123u && tri == 7u && rasterClass == kMpRasterClassHw
        && asfloat(depth32) > 0.0f) {
        g_out[dtid.x] = packed ^ sentinel;
    } else {
        g_out[dtid.x] = sentinel;
    }
}
)HLSL";

bool writeWrapper(const fs::path& absPath) {
    std::ofstream out(absPath, std::ios::out | std::ios::binary | std::ios::trunc);
    if (!out) return false;
    out << kWrapperShader;
    return out.good();
}

}  // namespace

int main() {
    const fs::path shaderRoot = ENIGMA_SHADER_ROOT_DIR;
    if (shaderRoot.empty()) {
        std::fprintf(stderr,
            "[mp_vis_pack_compile_test] ENIGMA_SHADER_ROOT_DIR not set\n");
        return 1;
    }

    // Place the wrapper alongside mp_vis_pack.hlsl so the DXC -I path
    // that points at the includer's parent directory resolves it.
    const fs::path wrapperAbs =
        shaderRoot / "micropoly" / "mp_vis_pack_compile_probe.hlsl";

    if (!writeWrapper(wrapperAbs)) {
        std::fprintf(stderr,
            "[mp_vis_pack_compile_test] failed to write wrapper shader: %s\n",
            wrapperAbs.string().c_str());
        return 1;
    }

    // Ensure the wrapper is deleted on exit so the shaders/ tree doesn't
    // accumulate test artifacts. RAII cleanup via a tiny scope guard.
    struct Cleanup {
        fs::path path;
        ~Cleanup() {
            std::error_code ec;
            fs::remove(path, ec);
        }
    } cleanup{wrapperAbs};

    enigma::test_infra::ShaderEntry entry{};
    entry.relativePath = "micropoly/mp_vis_pack_compile_probe.hlsl";
    entry.stage        = enigma::test_infra::SpirvStage::Compute;
    entry.entryPoint   = "CSMain";
    entry.goldenName   = "";  // unused — we don't diff against a golden

    // M3.2 closeout fix #5: MSVC does not unwind the stack when an exception
    // escapes main() uncaught (per C++ standard — this is implementation-
    // defined). That would leave the probe file on disk, polluting the
    // source tree for subsequent test runs / commits. Catching here forces
    // the Cleanup destructor to fire before we propagate a failure.
    try {
        const auto spirv = enigma::test_infra::compileOne(entry, shaderRoot);
        if (spirv.empty()) {
            std::fprintf(stderr,
                "[mp_vis_pack_compile_test] FAIL: compileOne returned empty\n");
            return 1;
        }

        std::printf(
            "[mp_vis_pack_compile_test] PASS: wrapper compiled to %zu bytes SPIR-V\n",
            spirv.size());
        return 0;
    } catch (const std::exception& ex) {
        std::fprintf(stderr,
            "[mp_vis_pack_compile_test] FAIL: exception: %s\n", ex.what());
        return 1;
    } catch (...) {
        std::fprintf(stderr,
            "[mp_vis_pack_compile_test] FAIL: unknown exception\n");
        return 1;
    }
}
