// visibility_buffer_vs.hlsl
// =========================
// Vertex shader fallback for the visibility buffer pass.
// Used on Min-tier GPUs that do not support VK_EXT_mesh_shader.
//
// Each draw call corresponds to one (instance, meshlet_local_idx) pair.
// Draw commands are generated by VisibilityBufferPass::buildVsFallbackDraws()
// with firstInstance = (instance_id << 16) | meshlet_local_idx.
//
// SV_VertexID: [0, triangle_count * 3) — indexes triangle + vertex within meshlet.
// SV_InstanceID: encodes instance_id (upper 16) + meshlet_local_idx (lower 16).
//
// Vertex data layout: 3 float4 per vertex (same packing as mesh shader path):
//   [vid*3+0] = (position.x, position.y, position.z, normal.x)
//   [vid*3+1] = (normal.y,   normal.z,   uv.x,       uv.y)
//   [vid*3+2] = (tangent.x,  tangent.y,  tangent.z,  tangent.w)

#include "common.hlsl"

// --- Bindless resource arrays ---
[[vk::binding(2, 0)]]
StructuredBuffer<float4> g_buffers[] : register(t0, space1);

[[vk::binding(5, 0)]]
RWByteAddressBuffer g_rwBuffers[] : register(u1, space0);

// --- Push constants (same struct as mesh shader path; VS ignores unused fields) ---
struct PushBlock {
    uint instanceBufferSlot;    // GpuInstance[]
    uint meshletBufferSlot;     // Meshlet[]
    uint _unused_survivingSlot; // survivingIdsSlot — not used in VS path
    uint meshletVerticesSlot;   // u32[] vertex index remapping
    uint meshletTrianglesSlot;  // packed u8 triangle indices
    uint cameraSlot;            // CameraData
    uint _unused_totalSurviving;
};

[[vk::push_constant]] PushBlock pc;

// --- GPU struct definitions (mirrors GpuInstance in GpuSceneBuffer.h) ---
struct GpuInstance {
    float4x4 transform;
    uint     meshlet_offset;
    uint     meshlet_count;
    uint     material_index;
    uint     vertex_buffer_slot;
    uint     vertex_base_offset;
    uint     _pad;
};

GpuInstance loadInstance(uint idx) {
    StructuredBuffer<float4> buf = g_buffers[NonUniformResourceIndex(pc.instanceBufferSlot)];
    const uint base = idx * 6;
    GpuInstance inst;
    inst.transform          = transpose(float4x4(buf[base + 0], buf[base + 1], buf[base + 2], buf[base + 3]));
    uint4 pack0             = asuint(buf[base + 4]);
    inst.meshlet_offset     = pack0.x;
    inst.meshlet_count      = pack0.y;
    inst.material_index     = pack0.z;
    inst.vertex_buffer_slot = pack0.w;
    uint4 pack1             = asuint(buf[base + 5]);
    inst.vertex_base_offset = pack1.x;
    inst._pad               = pack1.y;
    return inst;
}

struct Meshlet {
    uint   vertex_offset;
    uint   triangle_offset;
    uint   vertex_count;
    uint   triangle_count;
    float3 center;
    float  radius;
    float3 cone_axis;
    float  cone_cutoff;
};

Meshlet loadMeshlet(uint idx) {
    StructuredBuffer<float4> buf = g_buffers[NonUniformResourceIndex(pc.meshletBufferSlot)];
    const uint base = idx * 3;
    uint4  m0 = asuint(buf[base + 0]);
    float4 m1 = buf[base + 1];
    float4 m2 = buf[base + 2];
    Meshlet m;
    m.vertex_offset   = m0.x;
    m.triangle_offset = m0.y;
    m.vertex_count    = m0.z;
    m.triangle_count  = m0.w;
    m.center          = m1.xyz;
    m.radius          = m1.w;
    m.cone_axis       = m2.xyz;
    m.cone_cutoff     = m2.w;
    return m;
}

CameraData loadCamera(uint slot) {
    StructuredBuffer<float4> buf = g_buffers[NonUniformResourceIndex(slot)];
    CameraData cam;
    cam.view         = transpose(float4x4(buf[0],  buf[1],  buf[2],  buf[3]));
    cam.proj         = transpose(float4x4(buf[4],  buf[5],  buf[6],  buf[7]));
    cam.viewProj     = transpose(float4x4(buf[8],  buf[9],  buf[10], buf[11]));
    cam.prevViewProj = transpose(float4x4(buf[12], buf[13], buf[14], buf[15]));
    cam.invViewProj  = transpose(float4x4(buf[16], buf[17], buf[18], buf[19]));
    cam.worldPos     = buf[20];
    return cam;
}

// --- Vertex output ---
struct VSOutput {
    float4 sv_pos   : SV_Position;
    nointerpolation uint instance_id : TEXCOORD0;
};

// --- Vertex shader ---
VSOutput VSMain(uint vertexId : SV_VertexID, uint instanceIndex : SV_InstanceID) {
    // Decode packed firstInstance: upper 16 = instance_id, lower 16 = meshlet_local_idx.
    uint instance_id      = instanceIndex >> 16u;
    uint meshlet_local    = instanceIndex & 0xFFFFu;

    GpuInstance inst     = loadInstance(instance_id);
    uint global_meshlet  = inst.meshlet_offset + meshlet_local;
    Meshlet m            = loadMeshlet(global_meshlet);
    CameraData cam       = loadCamera(pc.cameraSlot);

    // Decode which triangle and which vertex within the triangle.
    uint triangle_idx    = vertexId / 3u;
    uint vertex_in_tri   = vertexId % 3u;

    // Read the local vertex index from the packed u8 triangle buffer.
    // Each triangle = 3 consecutive bytes at triangle_offset * 3.
    RWByteAddressBuffer triBuf = g_rwBuffers[NonUniformResourceIndex(pc.meshletTrianglesSlot)];
    uint byteOffset  = (m.triangle_offset + triangle_idx) * 3u + vertex_in_tri;
    uint wordOffset  = byteOffset & ~3u;
    uint byteShift   = (byteOffset & 3u) * 8u;
    uint word        = triBuf.Load(wordOffset);
    uint local_vert  = (word >> byteShift) & 0xFFu;

    // Remap through meshlet_vertices to get the global vertex index.
    StructuredBuffer<float4> vertexRemapBuf = g_buffers[NonUniformResourceIndex(pc.meshletVerticesSlot)];
    uint flatIdx     = m.vertex_offset + local_vert;
    uint float4Idx   = flatIdx / 4u;
    uint component   = flatIdx % 4u;
    uint4 packed     = asuint(vertexRemapBuf[float4Idx]);
    uint global_vert = packed[component];

    // Load vertex position from the per-instance vertex SSBO.
    StructuredBuffer<float4> vbuf = g_buffers[NonUniformResourceIndex(inst.vertex_buffer_slot)];
    float3 position = vbuf[global_vert * 3u + 0u].xyz;

    float4 worldPos = mul(inst.transform, float4(position, 1.0));
    float4 clipPos  = mul(cam.viewProj, worldPos);

    VSOutput output;
    output.sv_pos    = clipPos;
    output.instance_id = instance_id;
    return output;
}

// --- Pixel shader ---
// Writes packed (instance_id << 16) | primitive_id to the R32_UINT vis buffer.
uint PSMain(VSOutput input, uint primitiveId : SV_PrimitiveID) : SV_Target0 {
    return (input.instance_id << 16u) | (primitiveId & 0xFFFFu);
}
