#pragma once

#include "core/Types.h"

#include <volk.h>

#include <cstddef>

// Forward declare VMA handles.
struct VmaAllocator_T;
using VmaAllocator = VmaAllocator_T*;
struct VmaAllocation_T;
using VmaAllocation = VmaAllocation_T*;

namespace enigma::gfx {
class Device;
class Allocator;
class DescriptorAllocator;
} // namespace enigma::gfx

namespace enigma {

// Matches VkDrawMeshTasksIndirectCommandEXT.
struct alignas(4) DrawMeshTasksCommand {
    u32 groupCountX;
    u32 groupCountY;
    u32 groupCountZ;
};

// GPU buffer holding indirect draw commands generated by GpuCullPass.
// One command per surviving meshlet (after frustum culling).
// All three buffers are registered at binding 5 (UAV: RWByteAddressBuffer[])
// because GpuCullPass writes them atomically from a compute shader.
class IndirectDrawBuffer {
public:
    IndirectDrawBuffer(gfx::Device& device, gfx::Allocator& allocator,
                       gfx::DescriptorAllocator& descriptors);
    ~IndirectDrawBuffer();

    IndirectDrawBuffer(const IndirectDrawBuffer&)            = delete;
    IndirectDrawBuffer& operator=(const IndirectDrawBuffer&) = delete;

    // Resize to hold at least max_meshlets commands.
    void resize(size_t max_meshlets);

    // Reset draw count and surviving count to 0 (call each frame before cull).
    void reset_count(VkCommandBuffer cmd);

    // Copy the 24-byte count buffer (surviving + 5 plane counters) to a
    // HOST_VISIBLE readback buffer. Insert COMPUTE→TRANSFER barrier internally.
    // Call after the cull pass record, before queue submit.
    void record_count_readback(VkCommandBuffer cmd);

    // Map the readback buffer and log per-plane cull counts.
    // Call after the frame's timeline semaphore has been waited on (GPU done).
    void log_diag_plane_counts();

    VkBuffer buffer()           const { return m_buffer;           }
    VkBuffer count_buffer()     const { return m_count_buffer;     }
    VkBuffer surviving_buffer() const { return m_surviving_buffer; }

    // Bindless UAV slots (binding 5: RWByteAddressBuffer[]).
    u32 commands_slot()  const { return m_commands_slot;  }
    u32 count_slot()     const { return m_count_slot;     }
    u32 surviving_slot() const { return m_surviving_slot; }

    size_t capacity() const { return m_capacity; }

private:
    gfx::Device*              m_device      = nullptr;
    gfx::Allocator*           m_allocator   = nullptr;
    gfx::DescriptorAllocator* m_descriptors = nullptr;

    VkBuffer      m_buffer           = VK_NULL_HANDLE; // DrawMeshTasksCommand[]
    VmaAllocation m_alloc            = nullptr;
    VkBuffer      m_count_buffer     = VK_NULL_HANDLE; // u32[6]: surviving + 5 plane counters
    VmaAllocation m_count_alloc      = nullptr;
    VkBuffer      m_surviving_buffer = VK_NULL_HANDLE; // u32[] surviving meshlet IDs
    VmaAllocation m_surviving_alloc  = nullptr;
    VkBuffer      m_readback_buffer  = VK_NULL_HANDLE; // HOST_VISIBLE copy of count_buffer
    VmaAllocation m_readback_alloc   = nullptr;

    u32    m_commands_slot  = 0;
    u32    m_count_slot     = 0;
    u32    m_surviving_slot = 0;
    size_t m_capacity       = 0;
};

} // namespace enigma
